location = /health {
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    if ($request_method = OPTIONS) {
        return 204;
    }

    return 204;
}

location = /jenkins/login {
    satisfy any;

    set_real_ip_from 185.166.143.49;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    allow 151.70.128.163;
    allow 172.16.0.0/12;
    allow 192.168.1.0/24;
    allow 127.0.0.1;
    allow ::1;
    deny all;

    include /etc/nginx/conf.d/utils/proxy_params;
    proxy_pass http://jenkins:8080;
}

location = /jenkins/health {
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    if ($request_method = OPTIONS) {
        return 204;
    }

    return 204;
}

location /jenkins/ {
    include /etc/nginx/conf.d/utils/proxy_params;
    proxy_pass http://jenkins:8080;
}