jobs:
  - script: >
      pipelineJob('seed') {
          displayName('0-Init')
          description('Creates client repositories')

          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/abirall/jenkins.git')
                          }
                          branch('kom')
                      }
                  }
                  scriptPath('Jenkinsfile.seed')
              }
          }

          triggers {
              githubPush()
          }
      }