jenkins:
  systemMessage: "Jenkins configured using JCasC"

  numExecutors: 2

  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin123

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  git:
    installations:
      - name: "git"
        home: "/usr/bin/git"

jobs:
  - script: |
      job('freestyle-job') {
          description('My first freestyle job created by Job DSL')

          steps {
              shell('echo "First Free Style Job"')
          }
      }

      job('seed-job') {
          description('Seed Job for creating Pipeline Jobs')

          steps {
              jobDsl {
                  targets('jobs/seed-job.groovy')
              }
          }
      }